### ISSUE TITLE
시스템 명령어를 등록할 수 있음

### ISSUE THREAD

**Issue by g6123** [kirnot92/KappaBot#5]
예를 들어서, 아무런 경고나 오류 없이 `언제` 명령을 등록할 수 있고 `commands/` 폴더에도 파일이 추가되지만, 해당 명령을 사용하는 것은 불가능합니다.

```
> $등록 언제 테스트입니다.
> $언제
기본 명령어
$등록 [이름] [내용]
$삭제 [이름]
$목록
$언제 [이름]
$[이름]
```

**Comment by kirnot92** [comment]
추후 수평확장에 대해서 쪼금 고민이 됩니다만.... 일단은 목록을 수동으로 적어주었습니다
나중에 json같은데에 "등록": { "인자갯수": 2, "사용방법": "$등록 명령어 내용" } 뭐 이런식으로 적어서 관리한다던지 그러면 될 것 같아요 당장은 이렇게 막을게요

c5892468aa452d97ffccae9c64667c22d93eab23 에서 수정되었고 이슈닫슴니다

**Comment by kirnot92** [comment]
1332905fcd763930d8bd31e769679c5bd512de9c json으로 빼는 작업 끝낫습니다~
